{
  'x-forwarded-host': 'localhost:8080',
  'x-forwarded-proto': 'http',
  'x-forwarded-port': '8080',
  'x-forwarded-for': '127.0.0.1',
  'accept-language': 'es-419,es;q=0.9,en;q=0.8,ru;q=0.7',
  'accept-encoding': 'gzip, deflate, br',
  referer: 'http://localhost:8080/',
  'sec-fetch-dest': 'empty',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'same-origin',
  origin: 'http://localhost:8080',
  'sec-ch-ua-platform': '"macOS"',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
  'sec-ch-ua-mobile': '?0',
  'content-type': 'application/json',
  accept: 'application/json, text/plain, */*',
  'sec-ch-ua': '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
  'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '48',
  connection: 'close',
  host: 'localhost:3000'
}